### ISSUE TITLE
one-padding in dynamic_rnn.ipynb

### ISSUE THREAD

**Issue by lan2720** [dennybritz/tf-rnn#1]
Hi,
Thanks for your excelent tutorial! I learned  a lot from your code and the post.

One question is

```
tf.reset_default_graph()

# Create input data
X = np.random.randn(2, 10, 8)

# The second example is of length 6 
X[1,6,:] = 0
X_lengths = [10, 6]
```

The second example is of length 6. So I think if there is `X[1, 6:] = 0` rather than `X[1, 6, :] = 0`?

**Comment by dennybritz** [comment]
You're right, thanks for pointing it out! I fixed it in https://github.com/dennybritz/tf-rnn/commit/e74d438c7910555ce23d78fa16102ac92e523034
