### ISSUE TITLE
How to mix inference with training data based on queues

### ISSUE THREAD

**Issue by tokestermw** [dennybritz/tf-rnn#3]
Hi, thanks for the tutorial.

This is more of a question so sorry if it's not in the right place.

I'm training a language model using the queue and TFRecord method that you've described in the tutorials. I am able to feed in the batched / padded data into the TensorFlow graph and train the model.

Something like:

```
...
# queue for the data
batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name="y_batch"
)
...
# specify the model
embedding = tf.Variable(shape=(vocab_size, hidden_units), dtype=tf.float32)
embedded_input = tf.nn.embedding_lookup(
         embedding, batched_data, name="embedded_input")
...
# run the model
sess.run([train_op], feed_dict={})
...
```

I'd like to check the language model performance by generating words from the trained model. I would run the model however many steps to complete the sentence.

This requires me to feed in new data that's not part of the training data queue.

Previously, it was easy to use `feed_dict` and feed the new data in. But my model graph is entirely dependent on the `batched_data` above and so I wasn't sure how to add arbitrary data separate from or on top of the queue. This would be important at inference time as well.

Thanks!

**Comment by dennybritz** [comment]
I guess there are lots of different ways to do this: 

1. Create a different graph for training/inference (this is typically recommended) with different tensors as inputs.
2. Use `tf.contrib.learn.Estimator` and it's input function
3. Something like `sess.run([train_op], feed_dict={batched_data: YOUR_CUSTOM_DATA})` should work

**Comment by tokestermw** [comment]
Thanks.

Looks like 1) is the best.

For 3) I think batch size has to be equal to `batched_data` which may not be desirable.

Also, if I use `tf.train.batch` to batch and pad the training data, it seems like I'll need to write my own batch / pad function for inference.

I could use `tf.contrib.learn.run_n` on `tf.train.batch` of the new data but it's really slow.

**Comment by dennybritz** [comment]
> For 3) I think batch size has to be equal to `batched_data` which may not be desirable.

No, the batch dimensions should be `None`, which means it can be anything, i.e  you can feed a batch of size 1 even if you train with a batch size 16.

**Comment by tokestermw** [comment]
I might be doing this wrong, but this gives me a shape error. The first dimension for `batched_data` has the batch_size dimension instead of None.

```
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()
# [0, 1, 2, 3, 4 ,...]
x = tf.range(1, 10, name="x")
 
# A queue that outputs 0,1,2,3,...
range_q = tf.train.range_input_producer(limit=5, shuffle=False)
slice_end = range_q.dequeue()
 
# Slice x to variable length, i.e. [0], [0, 1], [0, 1, 2], ....
y = tf.slice(x, [0], [slice_end], name="y")
 
# Batch the variable length tensor with dynamic padding
batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name="y_batch"
)

tf.train.start_queue_runners(sess=sess)

new_data = np.array([0, 1, 2, 3, 4]).reshape(-1, 1)  # batch size 5 works
new_data = np.array([0, 1, 2, 3, 4, 5]).reshape(-1, 1)  # batch size 6 doesn't

sess.run([batched_data], feed_dict={batched_data: new_data})
 
```

**Comment by tokestermw** [comment]
Looks like you can use a placeholder default to switch between input data for training and inference.

http://stackoverflow.com/questions/36105763/how-to-handle-different-queue-batch-size-and-feed-value-batch-size-in-tensorflow
```
x = tf.placeholder_with_default(q.dequeue(), shape=[None, 100])
```

Or reuse some variables from the training graph to construct the inference graph.

http://stackoverflow.com/questions/40352841/how-can-i-build-a-tf-graph-that-has-separate-inference-and-training-parts
```
logits = model(train_data_node, True)
 loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(
      logits, train_labels_node))
 eval_prediction = tf.nn.softmax(model(eval_data))
```

Thanks

**Comment by amadupu** [comment]
in RNN where step sizes can vary across different batches, I don't think tf.placeholder_with_default is a viable option to feed data using feed_dict. if my statement is wrong please clarify

one option I could think is to create a separate pipeline for custom inputs and use it for validation and testing purpose on a trained model. But I feel feed dictionaries are much simpler as my input is a sentence or a word, however, I'm unsure how we can incorporate feed dictionaries here when the model is trained using input pipelines.
